name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build PDF
      uses: mahiguch/review-pdf-generator-action@master
    - name: upload as Artifacts
      uses: mahiguch/review-pdf-generator-action/upload-artifact@master
      env:
          INPUT_PATH: articles/GREE-BookFest8.pdf
